version: '{build}'

environment:
  project_name: ExcelMerge

image:
  - Visual Studio 2022

configuration:
  - Release

build_script:
  - dotnet restore
  - msbuild ExcelMerge.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: ExcelMerge\bin\release\
  name: test
deploy:
- provider: GitHub
  auth_token:
    secure: gMWeu6TO6xg0l6mxilJ3zkoYPhr5uV9VCkfcDw7EjSk3JZ+P32pdxUYhr4efPCPP
  artifact: test
  draft: true